# .github/workflows/deploy.yml

name: Deploy SAM Application

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://your-app-domain.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your project's python version

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 \
            | docker login --username AWS --password-stdin 988360969626.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and Push Docker image
        run: |
          docker buildx build \
            -t 988360969626.dkr.ecr.us-east-2.amazonaws.com/automated-rag-dev:latest \
            --platform linux/amd64 \
            -f chatbot/rag/rag_automated/rag_embedding_function/dockerfile-pgvector_dual \
            --provenance=false \
            --push .

      - name: Build SAM application
        # This command builds the source of your application
        run: sam build --template chatbot/rag/rag_automated/template.yaml

      - name: Deploy SAM application
        # This command packages and deploys your application to AWS
        run: |
          sam deploy \
            --template chatbot/rag/rag_automated/template.yaml \
            --no-confirm-changeset --no-fail-on-empty-changeset \
            --resolve-image-repos \
            --stack-name sam-app-hello-world \
            --capabilities CAPABILITY_IAM \
            --region us-east-2 \
            --parameter-overrides Environment=dev
