# .github/workflows/deploy.yml

name: Deploy SAM Application

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  rag-automated-build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://your-app-domain.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your project's python version

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 \
            | docker login --username AWS --password-stdin ${{vars.RAG_AUTOMATED_DOCKER_REGISTRY}}

      - name: Build and Push Docker image
        run: |
          # Generate unique tag (timestamp + commit SHA)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)
          DEV_RAG_IMAGE_TAG="${TIMESTAMP}-${COMMIT_SHA_SHORT}"

          docker buildx build \
            -t ${{vars.RAG_AUTOMATED_DOCKER_REGISTRY}}/${{vars.RAG_AUTOMATED_DOCKER_IMAGE_NAME}}:latest \
            -t ${{vars.RAG_AUTOMATED_DOCKER_REGISTRY}}/${{vars.RAG_AUTOMATED_DOCKER_IMAGE_NAME}}:$DEV_RAG_IMAGE_TAG \
            --platform linux/amd64 \
            -f chatbot/rag/rag_automated/rag_embedding_function/dockerfile-pgvector_dual \
            --provenance=false \
            --push .

          # Store the image tag for SAM deployment
          echo "DEV_RAG_IMAGE_TAG=$DEV_RAG_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build SAM application
        # This command builds the source of your application
        run: sam build --template chatbot/rag/rag_automated/template.yaml

      - name: Deploy SAM application
        # This command packages and deploys your application to AWS
        run: |
          sam deploy \
            --resolve-s3 \
            --no-confirm-changeset --no-fail-on-empty-changeset \
            --resolve-image-repos \
            --stack-name dev-rag-automated \
            --capabilities CAPABILITY_IAM \
            --region us-east-2 \
            --parameter-overrides "
              Environment=dev
              OpenAIApiKey=${{ secrets.OPENAI_API_KEY }}
              DbHost=${{ secrets.DB_HOST }}
              DbPort=${{ secrets.DB_PORT }}
              DbName=${{ secrets.DEV_DB_NAME }}
              DbUser=${{ secrets.DEV_DB_USER }}
              DbPassword=${{ secrets.DEV_DB_PASSWORD }}
              RagImageTag=${{ env.DEV_RAG_IMAGE_TAG }}
            "
